### PR TITLE
follow hu.dwim.asdf changes

### PR DESCRIPTION
**Pull request by attila-lendvai**

### CODE REVIEW

**Comment by attila-lendvai** [comment]
Sasha,

the thing with this pull request is that it needs to be pulled into cl-gpu at the same time when i update the hu.dwim universe in quicklisp, or at least close enough in time so that they are in the same quicklisp distribution.

are you reading this? can i count on you being around to pull this in sometimes in the next weeks?

**Comment by angavrilov** [comment]
Sure I can apply this pull request if you say it's the right change, but I haven't touched this in years and wouldn't be able to test it myself without lengthy remembering how to set up everything again. :)

**Comment by attila-lendvai** [comment]
see how useful README's are? :)

at least the dependency part will be solved by quicklisp, but i guess you mean the access to the underlying gpu libs...

can it at all work on a simple intel i5, without any ati or nvidia chip? if so i can try to test it.

**Comment by attila-lendvai** [comment]
unfortunately i cannot test any of this without a cuda card. maybe you could throw together quickly an opencl backend? ;)

but jokes aside, i've amended the patch and it's ready for merging, so please do so if you have the time. with this patch it will at least load when the next ql release is packaged.

**Comment by attila-lendvai** [comment]
@angavrilov, can you please merge this commit? Xach started to test the next release and it's showing up as a failing build.

**Comment by attila-lendvai** [comment]
thanks!

**Pull request merged**
